@startuml
User -> View: [click] select event
View -> HovedLayout: eventSelected()
HovedLayout -> EventList: getSelectedEvent
EventList -> HovedLayout: return event()
HovedLayout -> View: showEvent()
User -> View: [click] join event
View -> HovedLayout: joinEventRequest()
HovedLayout -> TicketLayout: change view
TicketLayout -> View: this = view
View --> User: input user info
User -> View: [input] user info
View -> TicketLayout: joinEvent()
alt payment required
TicketLayout -> PaymentAPI: open payment portal
PaymentAPI --> User: require payment method
User -> PaymentAPI: [action] payment performed
PaymentAPI -> TicketLayout: payment successful
TicketLayout -> View: [message] successful
View -> User: user joined event
else payment not required
TicketLayout -> View: [message] successful
View -> User: user joined event
end
@enduml