@startuml
Manager -> gruppe12.View: [click] new event
gruppe12.View -> HovedLayout: newEvent()
HovedLayout -> EventLayout: changeView()
EventLayout -> gruppe12.View: this = view
gruppe12.View --> Manager: input event info
Manager -> gruppe12.View: [input] event info
gruppe12.View -> EventLayout: createEvent()
alt event successfully created
EventLayout -> Database: storeEvent()
EventLayout -> gruppe12.View: [message] success
gruppe12.View -> Manager: event created
Database -> EventList: updateEventList()
else failed to create event
EventLayout -> EventLayout: error
EventLayout -> gruppe12.View: [message] error
gruppe12.View -> Manager: event creation failed
end
@enduml