@startuml
Manager -> LoginView: [input] login
LoginView -> Login: validateLogin()
Login -> Database: getUserList()
Database -> Login: return userList()
Login -> Login: matchUserList()
alt login successful
Login -> LoginView: return user()
LoginView -> Manager: login successful
else login failed
Login -> LoginView: [message] error
LoginView -> Manager: login failed
end
@enduml