@startuml

left to right direction
skinparam packageStyle rectangle
actor User as Basics
actor Manager as User

Basics <.- User : Manager can act as user

User -> (Login)
(Login) .> events : includes events
User -up-> (Create account)

(Login) -> (Edit account)
(Edit account) -> (Delete account)
rectangle events {
  User -- (Create event)
  User -- (Edit event)
  User -- (Delete event)
  User -- (Blacklist user from event)
  User -- (View event status)
  User -- (Assign managers to event)
}
@enduml