@startuml

left to right direction
skinparam packageStyle rectangle
actor User
User -> (Login)
(Login) .> events : includes events
User -up-> (Create account)

(Login) -> (Edit account)
(Edit account) -> (Delete account)

rectangle events {
  User -- (Join event)
  User -- (Leave event)
  User -- (pay for event)
  User -- (Search for event)
}
@enduml