@startuml
Manager -> HovedLayout: new event
HovedLayout -> EventLayout: new event
EventLayout -> Manager: input event info
Manager -> EventLayout: create event
alt event successfully created
EventLayout -> Database: store event
Database -> HovedLayout: update event list
HovedLayout -> Manager: event created
else failed to create event
EventLayout -> HovedLayout: error message
HovedLayout -> Manager: event not created
end
@enduml