@startuml
Manager -> HovedLayoutView: select event
HovedLayoutView -> HovedLayout: event selected

alt no event selected
HovedLayout -> HovedLayoutView: error message
HovedLayoutView -> Manager: you must select an event
end
HovedLayoutView -> HovedLayout: edit event
HovedLayout -> EventLayout: change view
EventLayout -> EventLayoutView: this view
EventLayoutView -> Manager: input event info
Manager -> EventLayoutView: inputed info
EventLayoutView -> EventLayout: create event
alt event successfully created
EventLayout -> Database: store event
Database -> HovedLayout: updated event list
HovedLayout -> HovedLayoutView: new list
HovedLayoutView -> Manager: event created
else failed to create event
EventLayout -> HovedLayout: error message
HovedLayout -> HovedLayoutView: error message
HovedLayoutView -> Manager: event not created
end
@enduml