@startuml
Manager -> View: [click] new event
View -> HovedLayout: newEvent()
HovedLayout -> EventLayout: changeView()
EventLayout -> View: this = view
View --> Manager: input event info
Manager -> View: [input] event info
View -> EventLayout: createEvent()
alt event successfully created
EventLayout -> Database: storeEvent()
EventLayout -> View: [message] success
View -> Manager: event created
Database -> EventList: updateEventList()
else failed to create event
EventLayout -> EventLayout: error
EventLayout -> View: [message] error
View -> Manager: event creation failed
end
@enduml