@startuml
User -> View: [click] delete account
View -> Account: deleteAccountRequest()
View --> User: type password
User -> View: [input] password
View -> Account: deleteAccount()
Account -> Database: deleteInDatabase()
Account -> View: [message] delete performed
View -> User: your account have been deleted, you'll be logged out
@enduml